import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Toaster } from 'sonner';

const inter = Inter({ 
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "We tripping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-dvh overflow-hidden">
      <body className={`${inter.className} antialiased h-dvh overflow-hidden m-0 p-0 tracking-[1px]`}>
        {children}
        <Toaster />
      </body>
    </html>
  );

}